/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multilevel;

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.AbstractBorder;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ACER
 */
public class EditProfile extends javax.swing.JFrame {

    private AbstractBorder circleBorder = new CircleBorder();

    static boolean maximized = true;
    int xMouse;
    int yMouse;

    private BufferedImage image;

    public EditProfile() {
        initComponents();
        imgX.setBorder(circleBorder);
        imgX.setForeground(new Color(0, 0, 0, 0));
        imgX.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgX = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txt_ID = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_alamat = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<>();
        btn_Reset = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_no_hp = new javax.swing.JTextField();
        txt_location = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1980, 1020));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgX.setBackground(new java.awt.Color(0, 0, 0));
        imgX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgX.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(imgX, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 190, 230));

        b1.setBackground(new java.awt.Color(255, 255, 255));
        b1.setText("Attach Image");
        b1.setBorder(null);
        b1.setFocusPainted(false);
        b1.setFocusable(false);
        b1.setRequestFocusEnabled(false);
        b1.setVerifyInputWhenFocusTarget(false);
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 210, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 250, 50));
        getContentPane().add(txt_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 220, -1));

        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 220, -1));

        jLabel1.setText("ID STAFF");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        jLabel2.setText("NAMA STAFF");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        jLabel3.setText("ALAMAT");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        jLabel4.setText("JENIS KELAMIN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, -1));

        txt_alamat.setColumns(20);
        txt_alamat.setRows(5);
        jScrollPane1.setViewportView(txt_alamat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 220, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki - laki", "perempuan" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 220, -1));

        btn_Reset.setText("Reset");
        btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, 110, 30));

        jLabel5.setText("NO HP");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));
        getContentPane().add(txt_no_hp, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 220, -1));

        txt_location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_locationActionPerformed(evt);
            }
        });
        getContentPane().add(txt_location, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 210, 30));

        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        getContentPane().add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 110, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        chooser.addChoosableFileFilter(fnef);
        File file = chooser.getSelectedFile();
        String filename = file.getAbsolutePath();

        BufferedImage bufferedImage = null;

        try {
            bufferedImage = ImageIO.read(new File(filename));
            filename = file.getAbsolutePath();
            txt_location.setText(filename);

            String newpath = "src/Upload/profile/";
            File directory = new File(newpath);
            if (!directory.exists()) {
                directory.mkdirs();
            }
            File sourceFile = null;
            File destinationFile = null;
            String extension = filename.substring(filename.lastIndexOf('.') + 1);
            sourceFile = new File(filename);
            Date tanggal_update = new Date();
            String tampilan = "yyyyMMddhhmmss";
            SimpleDateFormat fm = new SimpleDateFormat(tampilan);
            String tanggal = String.valueOf(fm.format(tanggal_update));
            destinationFile = new File(newpath + "/newImage" + tanggal.toString() + "." + extension);

            Files.copy(sourceFile.toPath(), destinationFile.toPath());

        } catch (IOException e) {
            e.printStackTrace();
        }

        Image scaledImage = bufferedImage.getScaledInstance(imgX.getWidth(), imgX.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(scaledImage);
        imgX.setIcon(image);

    }//GEN-LAST:event_b1ActionPerformed

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetActionPerformed
        // TODO add your handling code here:
        imgX.setIcon(null);
        txt_ID.setText(null);
        txt_nama.setText(null);
        txt_alamat.setText(null);
        txt_no_hp.setText(null);
        txt_location.setText(null);

    }//GEN-LAST:event_btn_ResetActionPerformed

    private void txt_locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_locationActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_locationActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "UPDATE staff SET nama_staff = '" + txt_nama.getText() + "', jk = '" + jComboBox1.getSelectedItem() + "',alamat = '" + txt_alamat.getText() + "',no_hp = '" + txt_no_hp.getText() + "',image = '"
                    + imgX.getIcon() + "' WHERE id_staff = '" + txt_ID.getText() + "'";
            System.out.println(sql);
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.PreparedStatement pst1 = conn.prepareStatement(sql);
            pst1.execute();
            JOptionPane.showMessageDialog(null, "penyimpanan data berhasil!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        txt_ID.setText(" ");
        txt_nama.setText(" ");
        txt_alamat.setText(" ");
        txt_no_hp.setText(" ");
        txt_location.setText(" ");
        imgX.setIcon(null);

    }//GEN-LAST:event_btn_saveActionPerformed
//private void inputimg (){
//    try {
//        
//    } catch (Exception e) {
//    }
//}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton btn_Reset;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel imgX;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextArea txt_alamat;
    private javax.swing.JTextField txt_location;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_no_hp;
    // End of variables declaration//GEN-END:variables
}
