/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multilevel;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class staff extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form staff
     */
    public staff() {
        initComponents();
        load_table();
        id_staff.disable();

        table.getTableHeader().setFont(new Font("Segeo UI", Font.BOLD, 12));
        table.getTableHeader().setOpaque(false);
        table.getTableHeader().setBackground(new Color(32, 136, 203));
        table.getTableHeader().setForeground(new Color(32, 136, 203));
        table.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panel_backgroun = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        panel_insert = new javax.swing.JPanel();
        nama = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        no_hp = new javax.swing.JLabel();
        jk = new javax.swing.JLabel();
        nama_staff = new javax.swing.JTextField();
        alamat_staff = new javax.swing.JTextField();
        no_hp_staff = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id_staff = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lable_backgroun = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(250, 22, 22));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-denied-30.png"))); // NOI18N
        jLabel4.setText("Delete");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 4, 100, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 150, 40));

        jPanel4.setBackground(new java.awt.Color(255, 228, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-update-30.png"))); // NOI18N
        jLabel3.setText("Update");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 120, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, 150, 40));

        panel_backgroun.setPreferredSize(new java.awt.Dimension(900, 550));
        panel_backgroun.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setFocusable(false);
        table.setGridColor(new java.awt.Color(153, 153, 153));
        table.setInheritsPopupMenu(true);
        table.setIntercellSpacing(new java.awt.Dimension(0, 0));
        table.setSelectionBackground(new java.awt.Color(255, 102, 102));
        table.setShowVerticalLines(false);
        table.getTableHeader().setReorderingAllowed(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        panel_backgroun.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 380, 290));

        panel_insert.setBackground(new java.awt.Color(255, 255, 255));
        panel_insert.setMinimumSize(new java.awt.Dimension(260, 260));
        panel_insert.setPreferredSize(new java.awt.Dimension(260, 200));
        panel_insert.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nama.setText("Nama  ");
        panel_insert.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        alamat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        alamat.setText("Alamat");
        panel_insert.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        no_hp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        no_hp.setText("No HP");
        panel_insert.add(no_hp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jk.setText("JK");
        panel_insert.add(jk, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 40, -1));
        panel_insert.add(nama_staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 160, -1));
        panel_insert.add(alamat_staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 160, -1));
        panel_insert.add(no_hp_staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 160, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki Laki", "Perempuan" }));
        panel_insert.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 160, -1));
        panel_insert.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, -1, -1));

        jPanel1.setBackground(new java.awt.Color(182, 103, 241));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-send-30.png"))); // NOI18N
        jLabel2.setText("Send");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 70, 40));

        panel_insert.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 130, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("ID Staff");
        panel_insert.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        panel_insert.add(id_staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 160, -1));

        panel_backgroun.add(panel_insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 280, 300));

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        panel_backgroun.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 190, 40));

        lable_backgroun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/adminstaff.jpg"))); // NOI18N
        lable_backgroun.setText("jLabel1");
        lable_backgroun.setPreferredSize(new java.awt.Dimension(900, 550));
        panel_backgroun.add(lable_backgroun, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, -1, 560));

        getContentPane().add(panel_backgroun, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        try {
            String sql = "insert into staff (nama_staff,alamat,no_hp,jk) values ('" + nama_staff.getText() + "','" + alamat_staff.getText() + "','" + no_hp_staff.getText() + "','" + jComboBox1.getSelectedItem() + "')";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            load_table();
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Simpan!");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        id_staff.setText("");
        nama_staff.setText("");
        alamat_staff.setText("");
        no_hp_staff.setText("");
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        try {
            new admin().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(staff.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM staff WHERE id_staff = '" + id_staff.getText() + "'";
            conn = (Connection) koneksi.configDB();
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Berhasil dihapus");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        id_staff.setText("");
        nama_staff.setText("");
        alamat_staff.setText("");
        no_hp_staff.setText("");
        load_table();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:

        int baris = table.getSelectedRow();
        if (baris != 1);
        {
            String no = table.getValueAt(baris, 0).toString();
            id_staff.setText(no);
            String name = table.getValueAt(baris, 1).toString();
            nama_staff.setText(name);
            String alamatt = table.getValueAt(baris, 2).toString();
            alamat_staff.setText(alamatt);
            String no_telfon = table.getValueAt(baris, 3).toString();
            no_hp_staff.setText(no_telfon);
        }
    }//GEN-LAST:event_tableMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        try {
            String sql = "UPDATE staff SET id_staff = '" + id_staff.getText() + "', nama_staff = '" + nama_staff.getText() + "',alamat = '" + alamat_staff.getText() + "',no_hp = '" + no_hp_staff.getText() + "',jk = '" + jComboBox1.getSelectedItem() + "' WHERE id_staff = '" + id_staff.getText() + "'";
            conn = (Connection) koneksi.configDB();
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "data berhasil diedit!");
            load_table();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "data gagal diedit!" + e.getMessage());
        }
        id_staff.setText("");
        nama_staff.setText("");
        alamat_staff.setText("");
        no_hp_staff.setText("");
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultiLevelLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamat;
    private javax.swing.JTextField alamat_staff;
    private javax.swing.JTextField id_staff;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jk;
    private javax.swing.JLabel lable_backgroun;
    private javax.swing.JLabel nama;
    private javax.swing.JTextField nama_staff;
    private javax.swing.JLabel no_hp;
    private javax.swing.JTextField no_hp_staff;
    private javax.swing.JPanel panel_backgroun;
    private javax.swing.JPanel panel_insert;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    private void load_table() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID STAFF");
        model.addColumn("Nama");
        model.addColumn("Alamat");
        model.addColumn("Kontak");
        model.addColumn("JK");

        try {
            String sql = "SELECT * FROM staff";
            java.sql.Connection konek = (Connection) koneksi.configDB();
            pst = konek.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1),
                    rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)
                });
                table.setModel(model);
            }
        } catch (SQLException e) {
        }
    }
}
